
language: node_js
node_js:
   - "0.10"

notifications:
  slack: tnt:dk3qZOnqruYAAlT9U3RZcPam

env:
  global:
    #GH_TOKEN
    - secure: "BvAZHbm6mefR1WNwsyxnsQYRCSDkcb1FgE8h3iytz00kDjmSdW3rD6g1KanLDiC11YRKXrCHrNOSqXkySIWzZL6LcskOyl6IoWA21pFiCbjDSG+rX2Vs0RlNKYoZMhgVUu5mCwOaX6jxlPldT3F1YVU1RAF9+CmmsJ7f0L6u0AI="
    #AWS_S3_KEY
    - secure: "QQuOonlNE9eJSl2+SyjZSj7H6/skahdVTcK+XPhdSgWgPZMhrGiAG23ATnuUbulZhZ9LWPjgveMmroPPzHWQCOxf5luWRwn96u29TV8IWpDmdPe6GA88e2MHxqctvtVI/XOBZmy4DdoqcCmsOWmeU733gir8WI647ZK9Na+8kQ0="
    #AWS_S3_SECRET
    - secure: "ZIhE0W2s+559TDMd75LtyI+HYidffBc3zexzE77mLhWBa4M4OvWLJjbpQn9xHtskskbhxmIVMf79ipfFVNIjq6VexJjutw6jq/lADBx+gAKEofZfPmK3S8u5hRQK4l7Jt8/NvYTS85ISCPkXQGnx9cDUIMxVgL5dmy2pnCQnBg0="
    #PHONEGAP_TOKEN
    - secure: "i2OsgcGteSF0fQAgCkvbB94SAqM9bpnJ/k5/OhDydEMT2wgMiRBEtEahsdpCIogFOfw3UpYeQSlyk46BzHNyxkMqEtrvrIMjoBxmshJcPnhVs6c02g53jonCfulR6qyqQUvgTpOA3wq+YFsuVgvnPU/hTYb0OGI/bnI7rR/o1QE="
    #- BUILD_ENV: ${TRAVIS_BRANCH}
    #- POST_TO_PHONEGAP: true
install:
    - npm install -g grunt-cli
    - npm install -g underscore-cli

after_success:
    - grunt deployS3

    #trigger phonegap build
    - curl -X PUT -d 'data={"pull":"true"}' https://build.phonegap.com/api/v1/apps/967572?auth_token=${PHONEGAP_TOKEN} | underscore pretty
    - curl -X POST -d 'data=''{"keys":{"ios":{"id":194221,"key_pw":"GF"}}}''' https://build.phonegap.com/api/v1/apps/967572/build?auth_token=${PHONEGAP_TOKEN} | underscore pretty
